"""add_sounds_favorites_playlists

Revision ID: b544e163bb7d
Revises: d3b22cbfa4e1
Create Date: 2026-03-27 15:10:43.517773

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b544e163bb7d'
down_revision: str | Sequence[str] | None = 'd3b22cbfa4e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sound_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_index('idx_favorites_user_sound', 'favorites', ['user_id', 'sound_id'], unique=True)
    op.create_table('playlist_sounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('sound_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playlist_sounds_playlist', 'playlist_sounds', ['playlist_id'], unique=False)
    op.create_index('idx_playlist_sounds_unique', 'playlist_sounds', ['playlist_id', 'sound_id'], unique=True)
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playlists_user_id', 'playlists', ['user_id'], unique=False)
    op.create_table('sounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tiktok_sound_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('play_url', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('trend_rank', sa.Integer(), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('last_trending_at', sa.DateTime(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_sound_id')
    )
    op.create_index('idx_sounds_tiktok_id', 'sounds', ['tiktok_sound_id'], unique=False)
    op.create_index('idx_sounds_title_artist', 'sounds', ['title', 'artist'], unique=False)
    op.create_index('idx_sounds_trend_rank', 'sounds', ['trend_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sounds_trend_rank', table_name='sounds')
    op.drop_index('idx_sounds_title_artist', table_name='sounds')
    op.drop_index('idx_sounds_tiktok_id', table_name='sounds')
    op.drop_table('sounds')
    op.drop_index('idx_playlists_user_id', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index('idx_playlist_sounds_unique', table_name='playlist_sounds')
    op.drop_index('idx_playlist_sounds_playlist', table_name='playlist_sounds')
    op.drop_table('playlist_sounds')
    op.drop_index('idx_favorites_user_sound', table_name='favorites')
    op.drop_index('idx_favorites_user_id', table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
